### ISSUE TITLE
Remove Ownable and Pausable from Core Proposal/Module Structure

### ISSUE THREAD

**Issue by 0xNuggan** [InverterNetwork/contracts#281]
Mentioned in #276:

While working with the whole owner/manager stuff for the RoleAuthorizer, I noticed that we aren't actually using the Manager role for anything outside of the milestoneManager and recurringPayment modules. We declare a lot of onlyAuthorizedOrManager() modifiers and never employ them.

- The Proposal never uses the modifier ever. The only mention of manager is the manager() func, that returns the Ownable owner() value. (Incidentally, we don't use Ownable.onlyOwner() anywhere in the proposal either).
- The Base Module only uses it onlyAuthorizedOrManager() for pause() and unpause()... which amounts to nothing since not a single Module uses whenPaused and whenUnPaused (We could remove the whole dependency I think… If a specific module wants to be pausable they can reimport)

So: We could remove the onlyAuthorizerOrManager modifier from the core contracts and together with it cull the Pausable and Ownable dependencies. This way, we could have a basic proposal with an isAuthorized function that effectively does the same as onlyOwner(), and if Modules need more roles they can enforce different IAuthorizer modules on initialization, f. ex. by specifying an ERC165 Interface.

**Comment by marvinkruse** [comment]
Should be covered already, let's check
