### ISSUE TITLE
Auditor Code Review - Recurring Payment Manager

### ISSUE THREAD

**Issue by 0xNuggan** [InverterNetwork/contracts#282]
Tagging @FHieser . These are the comments of the code review by the auditors. 
![RecurringPM-1](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/3ed0d10f-17e3-48a7-9fb7-61d427157aa6)
![RecurringPM-2](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/abe3c04d-fd56-4e90-8c9f-910501d65c0e)
![RecurringPM-3](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/caab2234-346f-429a-9b5f-70e0558ed336)
![RecurringPM-4](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/c98da0e4-ad77-4efd-a8ec-31cbf8230ff1)
![RecurringPM-5](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/0b5b7936-02bf-4d12-be1c-f5514b545d64)
![RecurringPM-6](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/4eba60af-0193-4b0c-bc33-5433f052c45b)
![RecurringPM-7](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/170e34c7-4a1f-4c95-9054-edef1bee8de6)
![RecurringPM-8](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/4abb5760-8bf7-4ec8-b3c7-8b8b8ab2ff51)
![RecurringPM-9](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/21f3562e-5be5-4706-a484-89e68775ae36)

**Comment by FHieser** [comment]
Directly relates to #272

**Comment by FHieser** [comment]
In regards of triggerFor:
-> would this be solved by giving it a onlyRole modifier? @0xNuggan

**Comment by FHieser** [comment]
Trigger call on removeRecurringPayment
I included a triggercall in here to make sure the address gets paid accordingly up onto that point
