### ISSUE TITLE
Auditor Code Review - General Comments

### ISSUE THREAD

**Issue by 0xNuggan** [InverterNetwork/contracts#284]
For the main Proposal code. This I think merits some discussion... Do we want the FundingManager to be a ERC20 itself? If it's the  way we are going to go we should enforce it on Interface level. I'd be generally against it, though :
![Proposal-1](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/50c53208-8059-4f81-8a3a-151d0e94d18e)
For the PaymentClient. We chose to remove this. Should we reconsider?
![PaymentClient-1](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/eb1bc939-e3dc-4421-b489-9d1696dcd604)
For the Module. Also mentioned in #281:
![Module-1](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/68a40299-9eb6-42a1-923a-f27b5c498b40)
For the MilestoneManager
![MilestoneManager-2](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/0ea3ec04-5b5a-4b9a-a189-e7dff15d0fec)
![MilestoneManager-1](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/7c9c1eb2-d018-45c9-bb59-1b6fbab49b14)

**Comment by FHieser** [comment]
"For the main Proposal code. This I think merits some discussion... Do we want the FundingManager to be a ERC20 itself? If it's the way we are going to go we should enforce it on Interface level. I'd be generally against it, though :
Proposal-1"
Move to rebasingFundingManager directly

**Comment by FHieser** [comment]
"For the PaymentClient. We chose to remove this. Should we reconsider?
PaymentClient-1"
StreamingPaymentProcessor should be able to instantly pay out funds thats why we removed it

**Comment by FHieser** [comment]
In regards of the index upcounting
I wouldnt include it in the library itself, because in the upcoming BountyModule we have multiple instances of lists that use the same index, which isnt possible with the index being moved to the library.
