### ISSUE TITLE
Reevaluate Manager Role

### ISSUE THREAD

**Issue by marvinkruse** [InverterNetwork/contracts#291]
Low prio discussion question: Do we still need it/want to keep it?

**Comment by FHieser** [comment]
"No"

The initial message of this comment was just "No" which is funny af, but also quite a dick move xD
I think we agreed on an internal call exactly what Marvin wrote below. We would revisit this and clean it up

**Comment by marvinkruse** [comment]
Notes from call: We agree that it most likely should be removed as it is not really used for anything important. So we should revisit this and remove if there still is anything related to it.
