### ISSUE TITLE
Documentation Overhaul

### ISSUE THREAD

**Issue by FHieser** [InverterNetwork/contracts#296]
Documentation is lacking in many points.
Please Overhaul it

**Comment by FHieser** [comment]
@marvinkruse Port docs to wiki

**Comment by marvinkruse** [comment]
Docs are ported to wiki, @saxenism is working on overhauling them. Should be done soon afaik.

**Comment by saxenism** [comment]
Yes, it's done.

Everyone is free to take a look at the [Inverter wiki](https://github.com/InverterNetwork/inverter-contracts/wiki) and collect all their suggestions and improvements in a separate GitHub issue.

Thanks.
