### ISSUE TITLE
Code review results - RecurringPaymentManager

### ISSUE THREAD

**Issue by 0xNuggan** [InverterNetwork/contracts#318]
Another picture dump for now - for the next one they'll probably do the PR directly in this repo so everybody can comment

![Screenshot from 2023-08-08 05-54-10](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/1a82fafc-c57c-45e4-a3b1-79c447d03938)
![Screenshot from 2023-08-08 05-54-20](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/7d6d7ed0-3d35-49db-80aa-8a97256e2875)
![Screenshot from 2023-08-08 05-54-30](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/c27434a0-b63b-4fa9-b68c-3f1def2f39a0)
![Screenshot from 2023-08-08 05-58-53](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/f4b69c60-a4ed-4a04-a77e-016e2782e0d4)
![Screenshot from 2023-08-08 05-59-00](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/e6e5216b-1d43-49b5-9500-6f463d333215)
![Screenshot from 2023-08-08 05-59-04](https://github.com/InverterNetwork/inverter-contracts/assets/82726722/a2bbdf0c-3b86-43f6-bf59-f89005464206)

**Comment by FHieser** [comment]
1. removeRecurringPayment -> use TriggerFor
2. Linked List usage
3. I cant access the link here?
4. dueTo not in the future / does not contain block.timestamp
5. dueTo: not in the future / does not contain block.timestamp
6. Seperate Payments for currentEpoch and past Epoch

**Comment by FHieser** [comment]
to 1. _triggerFor was not called properly so I fixed it accordingly. Now it should trigger the recurringPayment for the id that is to be removed

**Comment by FHieser** [comment]
2. Its a design decision
3. I dont really know what they want right here. @0xNuggan could you maybe clarify? (I also typed in the link manually and couldnt access it btw)

**Comment by FHieser** [comment]
4. and 5. Because the currentEpoch is calculated from the block.timestamp directly this comment is straight up wrong
LEts take a simple example:
uint epochLength= 25
uint timestamp= 40
CurrentEpoch is derived from block.timestamp
uint currentEpoch = timestamp/epochLength
=> currentEpoch = 1
If we add 1 to currentEpoch we get 2
multiplied with epochLength this is 50 which is higher than the timestamp and therefor in the future

**Comment by FHieser** [comment]
6. It would be good if you would revisit your old code reviews, because thats exactly what you criticized last time
The explanation why we did the change is there
