### ISSUE TITLE
StreamingPaymentProcessor Claim Function Parameter

### ISSUE THREAD

**Issue by FHieser** [InverterNetwork/contracts#322]
One thing i noticed while writing the tests is that the claimAll and the claimForSpecificWalletId functions in the StreamingPaymentProcessor need as a parameter IPaymentClient. I think for endusers it would be nice if they could just use the PaymentClient address to call upon these functions instead.

_Originally posted by @FHieser in https://github.com/InverterNetwork/inverter-contracts/issues/307#issuecomment-1655526187_

**Comment by saxenism** [comment]
Please review PR #325
