### ISSUE TITLE
Removal of unnecessary make pre-commit commands

### ISSUE THREAD

**Issue by FHieser** [InverterNetwork/contracts#333]
I would propose that we remove the gas snapshot and lcov portions out of the make pre-commit
In combination I would also remove the lcov files, because I think their not really used and they even make easy auto merges on the GitHub site nearly impossible.

In case we need the Lcov report we can create a separate make command that creates them explicitly and we exclude them via .gitignore

Any opinions on this?
@marvinkruse @0xNuggan @saxenism

**Comment by marvinkruse** [comment]
Call notes: We'll get rid of the lcov file and put stuff into a separate make command
