### ISSUE TITLE
BountyManager: Rename roles to avoid confusion

### ISSUE THREAD

**Issue by 0xNuggan** [InverterNetwork/contracts#335]
I think we should rename the roles in the BountyManager, since they aren't really "admins". They are just the users with that role. 
In addition to that, the RoleManager specifies an "admin" for each role, so we have f.ex. a "BountyManager-Claim-Admin-Role-Admin", which is confusing. I propose following renamings:
- BOUNTY_ADMIN_ROLE -> BOUNTY_ISSUER_ROLE
- CLAIM_ADMIN_ROLE -> CLAIMANT_ROLE
- VERIFY_ADMIN_ROLE -> VERIFIER_ROLE

Change should be straightforward, and ideally applied before handover. If I get a green light, I can add it to the open authorizer cleanup PR.

tagging @FHieser  and @marvinkruse

**Comment by FHieser** [comment]
This sounds reasonable
