### ISSUE TITLE
Security Review #350: RecurringPaymentProcessor findings

### ISSUE THREAD

**Issue by 0xNuggan** [InverterNetwork/contracts#365]
### This issue is linked to
- PR #350
### Explanation
- The removeRecurringPayment() may come into a situation where payments cannot be stopped. This was brough up in a previous review: [https://github.com/OmegaAudits/inverter-contracts/pull/7/files#r1278646633]
- 
### Category:
- Medium Severity

### Link to review comments
*Should be marked as done*
- [] https://github.com/InverterNetwork/inverter-contracts/pull/350#discussion_r1359796980

**Comment by FHieser** [comment]
The comment:
You fixed the "nothing happens" in that issue, but not the first comment on potentially not being able to stop payments. That comment was:

This may trigger ensureTokenBalance, and will fail in case there is not enough tokens pay older payments. So there can be a situation where if there are not enough tokens you can't remove a payment.
So you might want to allow claiming of the past payments but separately of the removal of the payment.

**Comment by FHieser** [comment]
My answer:
Your correct here that if triggerFor is not able to finish then removing a user also is not able to be resolved.
In my opinion this is still correct behavior, as being paid out as a user is required before removing them from the payment system.
I dont really see an easy way to split these functionalities into two separate functions without breaking that requirement

**Comment by FHieser** [comment]
My answer:
Your correct here that if triggerFor is not able to finish then removing a user also is not able to be resolved.
In my opinion this is still correct behavior, as being paid out as a user is required before removing them from the payment system.
I dont really see an easy way to split these functionalities into two separate functions without breaking that requirement
